export default {
  FETCH_USERS_FAILED: "FETCH_USERS_FAILED",
  FETCH_USERS_START: "FETCH_USERS_START",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  TOGGLE_USER_FAILED: "TOGGLE_USER_FAILED",
  TOGGLE_USER_START: "TOGGLE_USER_START",
  TOGGLE_USER_SUCCESS: "TOGGLE_USER_SUCCESS",
  SET_ALL_SELECTED: "SET_ALL_SELECTED",
  SELECT_ALL_USERS: "SELECT_ALL_USERS",
  SELECT_USER: "SELECT_USER"
};
